--LAB-3--

SELECT * FROM PERSON
SELECT * FROM DEPARTMENT

--1. Find all persons with their department name & code.

  SELECT PERSON.PERSONNAME,DEPARTMENT.DEPARTMENTNAME,DEPARTMENT.DEPARTMENTCODE
         FROM PERSON
		 INNER JOIN DEPARTMENT
		 ON PERSON.DEPARTMENTID = DEPARTMENT.DEPARTMENTID

		 
		  
--2. Give department wise maximum & minimum salary with department name.

   SELECT MAX(PERSON.SALARY) "MAX_SALARY",
          MIN(PERSON.SALARY) "MIN_SALARY",
		  DEPARTMENT.DEPARTMENTNAME
		  FROM PERSON
		  INNER JOIN DEPARTMENT
		  ON PERSON.DEPARTMENTID = DEPARTMENT.DEPARTMENTID
		  GROUP BY DEPARTMENT.DEPARTMENTNAME



--3. Find all departments whose total salary is exceeding 100000.

    SELECT SUM(PERSON.SALARY) "TOTAL_SALARY",
	       DEPARTMENT.DEPARTMENTNAME
		   FROM PERSON
		   INNER JOIN DEPARTMENT
		   ON PERSON.DEPARTMENTID = DEPARTMENT.DEPARTMENTID
		   GROUP BY  DEPARTMENT.DEPARTMENTNAME
		   HAVING SUM(PERSON.SALARY)>100000



--4. Retrieve person name, salary & department name who belongs to Jamnagar city.

  SELECT PERSON.PERSONNAME,PERSON.SALARY,DEPARTMENT.DEPARTMENTNAME
         FROM PERSON
		 INNER JOIN DEPARTMENT
		 ON PERSON.DEPARTMENTID = DEPARTMENT.DEPARTMENTID
		 WHERE CITY LIKE 'JAMNAGAR'



--5. Find all persons who does not belongs to any department.

  SELECT PERSONNAME FROM PERSON
  WHERE DEPARTMENTID IS NULL



--6. Find department wise person counts.

   SELECT COUNT(PERSON.PERSONNAME) "TOTAL_PERSON",DEPARTMENT.DEPARTMENTNAME
          FROM PERSON
          INNER JOIN DEPARTMENT
		  ON PERSON.DEPARTMENTID = DEPARTMENT.DEPARTMENTID
		  GROUP BY DEPARTMENT.DEPARTMENTNAME



--7. Find average salary of person who belongs to Ahmedabad city.
 
    SELECT AVG(PERSON.SALARY) "AVG_SALARY" 
	       FROM PERSON
		   WHERE CITY LIKE 'AHMEDABAD'


	    
--8. Produce Output Like: <PersonName> earns <Salary> from department <DepartmentName> monthly.(in single column)

  SELECT CONCAT(PERSON.PERSONNAME,' EARNS ',PERSON.SALARY,' FROM DEPARTMENT ',DEPARTMENT.DEPARTMENTNAME,' MONTHLY ')
         FROM PERSON
		 INNER JOIN DEPARTMENT
		 ON PERSON.DEPARTMENTID = DEPARTMENT.DEPARTMENTID



--9. List all departments who have no persons.

   SELECT DEPARTMENT.DEPARTMENTNAME
          FROM PERSON
		  INNER JOIN DEPARTMENT
		  ON PERSON.DEPARTMENTID = DEPARTMENT.DEPARTMENTID
		  WHERE DEPARTMENT.DEPARTMENTID = NULL



--10. Find city & department wise total, average & maximum salaries.

    SELECT PERSON.CITY,
	       SUM(PERSON.SALARY) "TOTAL_SALARY",
		   AVG(PERSON.SALARY) "AVG_SALARY",
		   MAX(PERSON.SALARY) "MAX_SALARY"
		   FROM PERSON
		   INNER JOIN DEPARTMENT
		   ON PERSON.DEPARTMENTID = DEPARTMENT.DEPARTMENTID
		   GROUP BY PERSON.CITY

	       

--11. Display Unique city names.
 
   SELECT DISTINCT(CITY) FROM PERSON


--12. List out department names in which more than two persons.

   SELECT DEPARTMENT.DEPARTMENTNAME,COUNT(PERSON.PERSONNAME)
          FROM PERSON
		  INNER JOIN DEPARTMENT
		  ON PERSON.DEPARTMENTID = DEPARTMENT.DEPARTMENTID
		  GROUP BY DEPARTMENT.DEPARTMENTNAME
		  HAVING COUNT(PERSON.PERSONNAME)>2


--13. Combine person name’s first three characters with city name’s last three characters in single column.

   SELECT CONCAT(LEFT(PERSONNAME,3),RIGHT(CITY,3)) FROM PERSON



--14. Give 10% increment in Computer department employee’s salary.

    SELECT PERSON.PERSONNAME,(PERSON.SALARY+PERSON.SALARY*0.1),DEPARTMENT.DEPARTMENTCODE
	       FROM PERSON
		   INNER JOIN DEPARTMENT
		   ON PERSON.DEPARTMENTID = DEPARTMENT.DEPARTMENTID
		   WHERE DEPARTMENTCODE='CE'

		


--15. Display all the person name’s who’s joining dates difference with current date is more than 365 days.

   SELECT PERSONNAME FROM PERSON
   WHERE (GETDATE()- JOININGDATE>365)